name: eqsormo
dependencies:
  - statsmodels>=0.11
  - tqdm>=4.0
  - numba>=0.51
  - numpy>=1.0
  - pandas>=1.0
  - dill>=0.3
  - scipy>=1.5
  - pyarrow>=0.15
  - python>=3.7
  # figure out how to mark these as dev dependencies
  - flake8>=3.7
  - pytest>=6
