# Publish Eqsormo to PyPI
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

# TODO figure out how to make this conditional on successful tests? Maybe? Or maybe we want to publish all tagged
# releases regardless of test failure?

name: Publish to Test PyPI and PyPI
on: push

jobs:
  build-publish:
    name: Build and publish to Test PyPI/PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel  # build dependencies
      - name: Build
        run: python setup.py sdist bdist_wheel
      
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
    
      # - name: Publish distribution 📦 to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.pypi_password }}
